version: "3.8"

services:
  # mongodb:
    # image: mongo
    # container_name: mongodb-25
    # ports:
    #   - "27017:27017"
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=admin
    #   - MONGO_INITDB_ROOT_PASSWORD=password
    # volumes:
    #   - mongodb_data:/data/db
  redis:
    image: redis/redis-stack
    container_name: redis-25
    ports:
      - 6379:6379
      - 8001:8001

volumes:
  mongodb_data:
    driver: local
